### ISSUE TITLE
Download of file(s) from both github and evilgames are going slow

### ISSUE THREAD

**Issue by axemwa** [GhostlyDark/OoT-Reloaded#1]
Download of files from both github and evilgames are going slow for me, 40kb/s on average are there any alternative links or a way u can boost the download speed for me as its like 4gb in ksize and saysing it will take a day to download, thnx.

**Comment by GhostlyDark** [comment]
Slow speed on two different sites?

As a one time offer:
https://mega.nz/folder/QyoG1RDD#Q4Jv6oGcMlAYPmJGDO9POg

If this is also slow for you, you should be angry at your internet provider.

**Comment by axemwa** [comment]
thankyou very much :) i appreciate it
