### ISSUE TITLE
Inside the Deku Tree Platform Shadows [Ship of Harkinian]

### ISSUE THREAD

**Issue by hunterzero99** [GhostlyDark/OoT-Reloaded#10]
Shadows on a lot of the platforms Inside the Deku Tree are backwards
![soh_2023-05-06_03-14-58](https://user-images.githubusercontent.com/40036150/236623882-aa82e1d7-1d31-4046-8201-5c848620bbdb.jpg)
![soh_2023-05-06_03-15-15](https://user-images.githubusercontent.com/40036150/236623883-b929aab7-95d3-4145-aefd-536f6d5584f9.jpg)

**Comment by GhostlyDark** [comment]
https://github.com/GhostlyDark/OoT-Reloaded-SoH/commit/ba8e1dbaba1003740f9f9aa4f5d06e13a455cc47
