### ISSUE TITLE
Corrupt Archives

### ISSUE THREAD

**Issue by SlotMachineGun777** [GhostlyDark/OoT-Reloaded#11]
Direct downloads from Github are corrupt please fix, and the hts files on the website dont actually load anything

**Comment by GhostlyDark** [comment]
Use latest GLideN64 (WIP builds), as the cache files are built with the new cache format. https://github.com/gonetz/GLideN64/commit/58faa2874a6eee20d1eb6ee6fde1f65f4f750e6d

GitHub files aren't corrupt, they work fine. I did upload the wrong files for the downscaled release though, which is being fixed right now.

If for whatever reason the textures still won't load, use the PNG files to generate your own cache.
