### ISSUE TITLE
[Switch] texture size exceeds maximum capacity on fat32

### ISSUE THREAD

**Issue by Gen0ne** [GhostlyDark/OoT-Reloaded#12]
Hi,

is there a way to cut the file in two parts to be able to store it in fat32 format ?

because currently the file is too large for fat32

Thank you :)

**Comment by GhostlyDark** [comment]
If it's for Switch, there's a tool for that use case:
https://github.com/Aionmagan/NSPsplitty

If it's for something else, you'd need to grab the downscaled PNG files and generate your own cache file, using HTS (hires texture storage) with compression enabled.
