### ISSUE TITLE
Newer version of the pack doesn't work and gets reduced to 1KB when i run the game.

### ISSUE THREAD

**Issue by Tasosgemah** [GhostlyDark/OoT-Reloaded#13]
I had an older version for a while (10.3.0) and decided to use the newer one.

Anyway, i downloaded the newest version of the mod and replaced the older one. But now, not only the textures don't work, when i go to the folder where the textures mods are, i see it got reduced to 1KB... The emulator literally killed the file.

I had to get the old one from a backup, which works again. But the newer doesn't. It just gets reduced to 1KB every time i try to load the game.

I use RetroArch 1.15.0 and the latest (as of now) Mupen64plus-next core, with GlideN64. Ofc, i have followed the instructions in the homepage, which is why this pack was working for me all this time. All i do is replace the old file with the new.

**Comment by GhostlyDark** [comment]
I tried it out just now with a fresh RetroArch v1.15.0 installation using mupen64plus-next. It works as it should.

Is there a non-empty hires_texture folder? If so, try deleting it.
Is texture compression turned on? Try turning it off.

The only difference between v10.3.0 and v10.4.0 is that the downscaled release (formerly named 1080p, currently 0.5x) is now uncompressed.

**Comment by Tasosgemah** [comment]
I did all that but it still doesn't work and also continues to kill the .hts file, turning it into a 1KB file. Though i managed to stop this behavior by making the file read only, the textures still don't show up.

Version 10.3.0 works normally.

**Comment by GhostlyDark** [comment]
Could the HTS file (or the downloaded archive) be corrupted on your end? At this point though, you might as well generate your own HTS file using the PNG pack, extracting the `THE LEGEND OF ZELDA` directory into the `hires_texture` folder, similar to how the HTS file goes into the cache folder.

**Comment by Tasosgemah** [comment]
I downloaded multiple times so it couldn't be corrupted all those times.

I'll try to generate the HTS like you said. Is that something that can be done outside the game?

**Comment by GhostlyDark** [comment]
It gets generated once you boot up the game. For RetroArch, the screen is going to stay black. It'll take some time to generate, with no indication of progress.

**Comment by Tasosgemah** [comment]
OK, i created a folder named "hires_texture", in the same place the other folders like the "cache" folder is.

I extracted the .png zip inside that folder and it created a "THE LEGEND OF ZELDA" subfolder with all the files inside.

So the structure is "hires_texture\THE LEGEND OF ZELDA\"

Nothing happens. I load the game and there is no black screen or anything that indicates something is happening in the background. It just loads the normal textures.

**Comment by Tasosgemah** [comment]
Ok, i managed to make this work. I had to enable "use enchanted Hi-Res Storage" in the core options, which is something i didn't have to enable before and i missed it.
