### ISSUE TITLE
No Issue (Just a question)

### ISSUE THREAD

**Issue by IanSkelskey** [GhostlyDark/OoT-Reloaded#14]
Do you have a somewhat automated solution for porting textures made for Dolphin to Ship of Harkinian? @GhostlyDark 
Sorry to clutter your issues, but I couldn't find any other way to reach you. Email me or message me here if you care to discuss.

ianskelskey@gmail.com

**Comment by GhostlyDark** [comment]
There is no automated solution. The extracted textures from Ship of Harkinian look broken most of the time, so there is absolutely no way to visually match them with the dumps from GLideN64 or Dolphin, using Luni's Texture Conversion Toolbox for instance. All of the SoH textures have been ported over manually.

**Comment by IanSkelskey** [comment]
Brutal. Thanks for getting back to me!
