### ISSUE TITLE
Textures don't work on the Russian version of the game.

### ISSUE THREAD

**Issue by Siigonis** [GhostlyDark/OoT-Reloaded#15]
It is indicated that there is support, but what kind of translation and which version? As far as I know, there is a translation from only one author, and the final version is 2.32 - https://shedevr.org.ru/zelda64rus/translations.html#oot. Textures don't work with it. Can you please check and add support?

Retroarch 1.17.0, Mupen64plus-next 2.6. Textures 10.4.0 - 0.5x. There are no problems in the game with the English language, the textures work and they are gorgeous.

**Comment by GhostlyDark** [comment]
The one that is part of https://github.com/Admentus64/Patcher64Plus-Tool, which contains an edited version of that v2.32 you mentioned, which I personally modified. If I recall correctly, the original patch changes the internal ROM name, which breaks texture loading. You can either patch the game with Patcher64+ or change the internal ROM name back to `THE LEGEND OF ZELDA` using something like `N64 ROM Renamer` or via a simple hex edit (if you know what that is). You may need to rename your save file, in case you played a ROM with the Russian patch for a while.

**Comment by Siigonis** [comment]
Understood, thanks. I don't know why, but when editing via Hex, the rom didn't start, probably did something wrong, but everything worked through Patcher64+.
