### ISSUE TITLE
Typo in French Zora River title

### ISSUE THREAD

**Issue by Jean-Daniel** [GhostlyDark/OoT-Reloaded#17]
The French Zora River title is spelled "Flueve Zora" instead of "Fleuve Zora" in the file:

[THE LEGEND OF ZELDA/UI/Language/Location Titles/French/THE LEGEND OF ZELDA#038FB779#3#1_all.png](https://github.com/GhostlyDark/OoT-Reloaded/blob/33af8f52a3077059fbc54415ec00b71924dbcb8c/THE%20LEGEND%20OF%20ZELDA/UI/Language/Location%20Titles/French/THE%20LEGEND%20OF%20ZELDA%23038FB779%233%231_all.png)

**Comment by GhostlyDark** [comment]
Thanks for reporting. Fixed via 6949fa7b000e451d5c66818d0b055f3d9ff611c7.
