### ISSUE TITLE
Texture Does'nt load anymore in Bizhawk with the provided file from the homepage.

### ISSUE THREAD

**Issue by inubashiri1** [GhostlyDark/OoT-Reloaded#18]
So Like the title is saying i tried to run the texture pack in bizhawk but it didnt work anymore tried everything bizhawk related to fix that which includes backrolling to at least version 2.6.3 (support for hts files was since bizhawk 2.7 i believe)
that means on version 2.9.1/2.8/2.7/2.6.3 it cant load the pack

The only way i got it to work was by Downloading it in on PNG files and then run it through Projekt 64 to compile it to an hts file.

My question here is if you changed the file itself or the format and what need to be done with bizhawk to get it working again.
I tried my luck with the bizhawk community already and they cant figure out why its not working

also tried Djipi’s 2016 Cell Shade style Ocarina of Time texture pack also doesnt work so i might to contact him as well.

Important to mention it worked before but thats like almost half a year ago.

**Comment by GhostlyDark** [comment]
The cache format has changed (it now remembers texture format and size, it ignored it previously). The current cache files are built with modern GLideN64 versions, but BizHawk uses out-of-date plugin and core code. The workaround is - as you noticed - to compile it with an older version of GLideN64. Unfortunately, there are downsides to continue using the old format, so I'm not providing old builds anymore.

Djipi's texture packs should work however, unless you downloaded a file that somebody has rebuilt with a newer GLideN64 build.

**Comment by inubashiri1** [comment]
yeah i believe Djipi.s updated as well so i need to wait for a new bizhawk version with a up to date GlideN64 plugin.

**Comment by GhostlyDark** [comment]
That requires the devs updating the mupen64plus-core first, which by this point is well over a decade old. I wouldn't wait on that.
