### ISSUE TITLE
Eye Texture Bug

### ISSUE THREAD

**Issue by RafaelDeJongh** [GhostlyDark/OoT-Reloaded#19]
I couldn't directly find it when searching but after applying your texture pack mod all the characters have some weird double eye issue. Is this a known problem and if so is there a potential fix as the texture pack itself is absolutely amazing! 

![PXL_20240924_030803876.MP.jpg](https://github.com/user-attachments/assets/f322e0bb-631c-4a69-86d8-eabb6f7db679)

![PXL_20240924_031202443.MP.jpg](https://github.com/user-attachments/assets/0ebd53a3-2c85-4199-9339-3c9cb5fe46b0)

**Comment by GhostlyDark** [comment]
I assume you are using Ship of Harkinian with custom character models. HD textures can be incompatible with textures from custom models, mainly animated textures (eyes and mouths). 

There's no real solution for this, as the texture pack isn't at fault here. Either don't use custom models or delete the textures from the pack that have conflicts.
