### ISSUE TITLE
Making own cache doesn't do skybox

### ISSUE THREAD

**Issue by itsSilverlink** [GhostlyDark/OoT-Reloaded#3]
Hey,

I downloaded the PNG files to edit some textures so that instead of the C buttons you can use the "Switch Pro Buttons" and now when I'm using Mupen64 / Modload64 to remake the cache it doesn't load in the skybox as far as i can see. 

It makes 22GB cache file which is around the size of the HTC file it self also. 

It seems that the file selection screen also doesn't pick up the background textures.

![File Selection Screen](https://i.imgur.com/eRqGEme.png)
![Hyrule Field](https://i.imgur.com/oWs0Ovc.png)
![Folder](https://i.imgur.com/QOF2xCo.png)

Can you help me fix this or do i need to create the cache another way?

**Comment by GhostlyDark** [comment]
You need to use a current GLideN64 WIP build to generate the cache.
https://ci.appveyor.com/project/gonetz/gliden64/history

The reason for this is the usage of wildcarded textures for the skyboxes, which in that particular case gets rid of duplicate textures and improves performance significantly. The wildcard feature was implemented early this year, so it's fairly new.
(You can use a more up-to-date build of GLideN64 to build a cache file that will work on older versions of the plugin. Textures that use a wildcard on the second hash like the skyboxes do will also load in older versions of the plugin.)

I don't know if ModLoader allows you to update GLideN64 without breaking everything. So in case you aren't able to update, you can replace the files with the old skybox textures:
https://mega.nz/file/srJilZJB#AUK8MvEtR0AXEPseI6dt_lFWilofZhE1hIMhnc1Kxn8

**Comment by itsSilverlink** [comment]
Thank you for this. Updating the GLideN64 in Modloader worked like a charm!
