### ISSUE TITLE
No HTC package for Bizhawk?

### ISSUE THREAD

**Issue by Nicholas-Steel** [GhostlyDark/OoT-Reloaded#4]
I've heard there used to be a HTC package available that worked with Bizhawk. Could you please make such a package available, or update the custom interim build of Bizhawk to be based on the final 2.6.2 release?

Thanks.

**Comment by GhostlyDark** [comment]
I axed the HTC build as I successfully built an updated GLideN64 version for BizHawk that supports HTS. You can find it here:
https://github.com/GhostlyDark/GLideN64/releases/latest

Bundled with a custom build of BizHawk that supports Rumble:
https://github.com/GhostlyDark/BizHawk/releases/latest

As a nice side effect, the Owl and Shell Blades don't have texture issues anymore with this build. I don't plan on bringing back HTC builds, but please let me know if you have any issues using this version of GLideN64 and I may reupload one for the time being.

**Comment by GhostlyDark** [comment]
BizHawk now includes Rumble support and an updated GLideN64 build upstream. You are now able to configure it to either use HTC or HTS.

Until a new stable build for it releases, you can downloads builds from AppVeyor:
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

The first up-to-date build with the necessary changes is also available here:
https://github.com/GhostlyDark/bizhawk-co-op/releases/tag/2021-07-21
