### ISSUE TITLE
MM Links textures doesn't load

### ISSUE THREAD

**Issue by XebasBlox** [GhostlyDark/OoT-Reloaded#5]
Some textures of MM Links doesn't load on the version 10.0.0:

![MM Adult Link texture 1](https://user-images.githubusercontent.com/96048224/146127908-25a6bb92-0054-483c-9f36-453cd327739f.PNG)
![MM Adult Link texture 2](https://user-images.githubusercontent.com/96048224/146127947-3ca4cded-b5ab-44b8-b588-b5888faaf959.PNG)
![MM Adult Link texture 3](https://user-images.githubusercontent.com/96048224/146127962-fc37a917-ae5e-4613-8bdc-6a5d5cea9b8f.PNG)
![MM Adult Link texture 4](https://user-images.githubusercontent.com/96048224/146127981-fd9c7a1b-59dc-4801-8d89-232b09993fc8.PNG)
![MM Adult Link texture 5](https://user-images.githubusercontent.com/96048224/146127991-37d5aeac-5cbf-48a7-a11d-ab62edcf3d45.PNG)
![MM Adult Link texture 6](https://user-images.githubusercontent.com/96048224/146127997-de723f29-fb1b-4767-a2d0-4e2f061433c4.PNG)

The randomizer rom was patched without Patcher64.

In previous versions, the textures were working fine except for the eyes of Adult Link and the Master Sword textures.

The earrings of Adult Link are always black in the randomizer rom.

The eyes of Young Link shown on the picture, never load no matter if the rom was patched with Patcher 64+.

Any way to fix it?

**Comment by GhostlyDark** [comment]
The textures are part of the pack, but I did remove various textures from older versions of the models. It seems like you are using an outdated MM Adult Link. Please make sure to use v2.0 of the model and the textures should load.

MM Young Link's eyes appear fine on my end. I can't reproduce that using Patcher64+ v15.1.4.

As a sidenote, one is able to use the Patcher to patch in any of the models into Rando after enabling the option to ignore checksums. Just make sure not to patch in anything that may break the Rando ROM (like text related things, speedups that already exist, etc.).

**Comment by XebasBlox** [comment]
Updated everything and did what you said. The textures are working alright.

Patched again the vanilla rom with Patcher 64+ v15.1.4, and MM Young Link's eyes loaded fine too, I think I was using an old version of Young Link too.

It seems that the issue is solved.

Thank you so much for helping!
