### ISSUE TITLE
I may be being a dummy but it's not working in RetroArch even tho i have all the boxes ticked

### ISSUE THREAD

**Issue by Rickroll10000** [GhostlyDark/OoT-Reloaded#7]
I've been trying get the oot reloaded pack to work the other ones you've made work just fine with all the instructions you put just not oot It's driving me crazy because it worked before

**Comment by GhostlyDark** [comment]
GitHub isn't the place to ask for setup support and you didn't give enough information.
What HTS file did you download? What settings did you apply? What platform are you trying to run it on?

I confirmed that it works with current mupen64plus-nx as expected.
![image](https://user-images.githubusercontent.com/31742919/157229651-687d7f74-77b2-49d5-8fc5-fe48fe100498.png)

If you need further assistance, feel free to join our Discord.
https://discord.gg/P22GGzz
