### ISSUE TITLE
Need permission to post converted textures on SOH Discord

### ISSUE THREAD

**Issue by Jaddey23** [GhostlyDark/OoT-Reloaded#9]
Hi, a friend converted your textures to work with special k on the SOH pc port. I was wanting permission to post the mega link on the SOH Discord
Or you could upload the converted textures on your site

They work great you just have to go into graphics settings on the pc port and set texture filtering to linear and restart the game

**Comment by GhostlyDark** [comment]
I recommend waiting for true HD texture support for Ship of Harkinian.
https://github.com/HarbourMasters/Shipwright/pull/463

There is already a port of OoT Reloaded in the works - by myself - but not released, as there is no official way to load them right now, until the linked PR is merged. Even then, it'll need more work from both the SoH devs and me to fix any remaining texture issues that I can't test for as of now. It's also the reason why I have to refuse to upload the ported textures onto my website.

However, you are free to reuse anything you need as long as you properly credit whatever work you borrow from.
You may post this on Discord, but only if you put proper credits next to the link.

**Comment by Jaddey23** [comment]
Ok thanks so much! I might do the true hd texture support and replay once they add master quest support to SOH
